version: "3"
services: 
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/caches:/data-cache
    environment:
      - TZ=Asia/Bangkok
      - NGINX_PORT=80
    restart: always
    networks:
      - frontend-network

  web01:
    image: porchn/php5.6-apache:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ./docroot:/var/www/html
      - log:/log
    environment:
      - TZ=Asia/Bangkok
    networks:
      - frontend-network
      - backend-network
    hostname: web
    restart: always

  mysql:
    image: mariadb:10


    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      # MYSQL_ROOT_PASSWORD: abc123
      # MYSQL_DATABASE: diyretro_db1
      # MYSQL_USER: devuser
      # MYSQL_PASSWORD: devpass
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=abc123
      - "MYSQL_ROOT_HOST=%"

    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1G   
    ports:
      - 8080:80
    restart: always
    networks:
      - backend-network

volumes:
  log:

networks:
  frontend-network:
  backend-network: